
## ~~~ TO BE EDITED TO BE TAILORED TO THE CLUSTER ~~~
##
## Settings for fictive CW23
##
## Updated: 04/05/2023

---
cluster_name: "CW23"
location: "EH8"
api-carbonintensity: carbonintensity.org.uk
integration-method: sum
PUE: 1.20 # > 1
partitions:
  CPU_partition:
    type: CPU # CPU or GPU
    model: "Xeon Gold 6142"
    TDP: 9.4 # in W, per core
  GPU_partition:
    type: GPU
    model: "NVIDIA A100-SXM-80GB GPUs" # from https://docs.hpc.cam.ac.uk/hpc/user-guide/a100.html
    TDP: 300 # from https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/pdf/PB-10577-001_v02.pdf
    CPU_model: "AMD EPYC 7763" # from HPC team
    TDP_CPU: 4.4 # from https://www.amd.com/fr/products/cpu/amd-epyc-7763
