"Energy-Charts API: day-ahead price and renewable share signal"

# pyright: reportUnknownArgumentType=none, reportUnknownVariableType=none, reportAny=none

from datetime import datetime, timedelta
from importlib.resources import files
from typing import Any, ClassVar
from urllib.parse import quote


from ..exceptions import InvalidLocationError
from ..forecast import PointEstimate, Timeseries
from .base import (
    BaseProvider,
    LocationGroup,
    align_to_resolution,
    fetch_url,
    provider,
    resolve_metric,
)

INVALID_ZONE_MESSAGE = (
    "{location}. The 'price' metric needs an Energy-Charts bidding zone code, "
    "e.g. 'DE-LU', 'FR', 'IT-North'. See cats/data/energycharts_zones.txt for the "
    "full list. Note this is unrelated to the plain country codes used by the "
    "'renewables' metric."
)
INVALID_COUNTRY_MESSAGE = (
    "{location}. The 'renewables' metric needs an Energy-Charts country code, "
    "e.g. 'de', 'fr', 'it'. See EU_RENEWABLES_COUNTRIES for the full list. Note "
    "this is unrelated to the bidding zone codes used by the 'price' metric."
)

# List of bidding zones supported by the Energy-Charts /v2/price endpoint, as
# documented at https://api.energy-charts.info/ (captured 2026-09-29). Short,
# fixed list so it is hardcoded directly rather than generated by a script
# (cf. scripts/uk_outcodes.py for uk_outcodes.txt). Great Britain is not part
# of this list: GB is outside the EU single day-ahead market coupling that
# this data is sourced from, and is instead covered by the octopus.energy provider.
_ZONE_NAMES: list[str] = (
    (files("cats") / "data" / "energycharts_zones.txt").read_text().split()
)
# Energy-Charts zone codes use mixed case (e.g. "DE-LU", "IT-Calabria"), unlike
# the all-uppercase codes used by the other bundled providers, so lookups are
# done case-insensitively but the canonical (as-published) casing is always
# sent to the API.
ENERGYCHARTS_ZONES: dict[str, str] = {z.upper(): z for z in _ZONE_NAMES}

# Countries with real data from the Energy-Charts /v2/signal endpoint. The
# API's own query-parameter validation accepts a wider set ("uk", "ba", "cy",
# "ge", "ie", "md", "rs", "ua", "xk" among others) but returns an empty
# `data: []` for several of them - confirmed live on 2026-09-29 by checking
# actual data point counts per country, not just which codes the API's error
# message lists as syntactically valid. This is a country-level dataset (not
# the bidding-zone granularity used by /v2/price), and its coverage differs
# slightly from the price zones: e.g. it has no split for Norway/Sweden
# (single "no"/"se" instead of NO1-5/SE1-4).
EU_RENEWABLES_COUNTRIES: frozenset[str] = frozenset(
    {
        "at",
        "be",
        "bg",
        "ch",
        "cz",
        "de",
        "dk",
        "ee",
        "es",
        "fi",
        "fr",
        "gr",
        "hr",
        "hu",
        "it",
        "lt",
        "lu",
        "lv",
        "me",
        "mk",
        "nl",
        "no",
        "pl",
        "pt",
        "ro",
        "se",
        "si",
        "sk",
    }
)


@provider("energy-charts.info")
class EnergyChartsProvider(BaseProvider):
    """
    Provider for the Fraunhofer ISE Energy-Charts API

    This can be used by passing the --api='energy-charts.info' command line
    argument. No authentication is required. Supports two metrics from two
    different sub-endpoints of the same portal (selected with --metric):

    - price (default): day-ahead electricity spot price, in EUR/MWh, across
      most of continental Europe (54 bidding zones at time of writing, see
      cats/data/energycharts_zones.txt), location specified as a bidding
      zone code, e.g. 'DE-LU', 'FR', 'IT-North'. 15 minute resolution.
      Day-ahead prices are typically published once per day around
      12:00-15:00 CET for the following day, so the effective forecast
      horizon into the future varies through the day even though
      get_max_duration_minutes() reports a fixed nominal maximum. Not
      compatible with --footprint, which only applies when
      forecast.metric == "Carbon intensity".

    - renewables: non-renewable generation share (100 minus the renewable
      percentage the API reports), across a country-level set that differs
      from the price bidding zones (see EU_RENEWABLES_COUNTRIES), location
      specified as a plain two-letter country code, e.g. 'de', 'fr', 'it'.
      15 minute resolution, but this endpoint only ever appears to return
      data for the current day (00:00-23:45 local), even when explicit
      start/end query parameters are supplied requesting a later date -
      get_max_duration_minutes() reports a correspondingly modest nominal
      maximum for this metric. Values can legitimately be negative:
      renewable generation can exceed 100% of domestic load around midday
      in high-solar/wind countries (the surplus is exported), which shows
      up here as a negative "non-renewable share". This is real data, not a
      bug. Lower is still "better" here, matching CATS' minimum-average-
      window scheduler, whereas raw renewable share would need "higher is
      better" (which the scheduler does not support). Not compatible with
      --footprint. Great Britain is not covered ("uk" is a country code the
      underlying API accepts but has no real data for); use
      carbonintensity.org.uk's renewables metric for GB instead.

    price and renewables use different location encodings (bidding zone vs.
    plain country code) since that is how the underlying API exposes them;
    validate_location() accepts either (returning whichever it matches),
    while get_data() applies a metric-specific, stricter check once the
    metric is known.
    """

    BASE_URL: ClassVar[str] = "https://api.energy-charts.info"
    SUPPORTED_METRICS: ClassVar[frozenset[str]] = frozenset({"price", "renewables"})
    DEFAULT_METRIC: ClassVar[str] = "price"

    def validate_location(self, location: str | None) -> str:
        if location is None:
            raise InvalidLocationError(
                "Must provide location for Energy-Charts provider"
            )
        zone = ENERGYCHARTS_ZONES.get(location.upper())
        if zone is not None:
            return zone
        country = location.lower()
        if country in EU_RENEWABLES_COUNTRIES:
            return country
        raise InvalidLocationError(
            f"{location}. Not a recognised Energy-Charts bidding zone or country code."
        )

    def _validate_price_location(self, location: str | None) -> str:
        if location is None:
            raise InvalidLocationError(
                "Must provide location (bidding zone) for the 'price' metric"
            )
        zone = ENERGYCHARTS_ZONES.get(location.upper())
        if zone is None:
            raise InvalidLocationError(INVALID_ZONE_MESSAGE.format(location=location))
        return zone

    def _validate_renewables_location(self, location: str | None) -> str:
        if location is None:
            raise InvalidLocationError(
                "Must provide location (country code) for the 'renewables' metric"
            )
        country = location.lower()
        if country not in EU_RENEWABLES_COUNTRIES:
            raise InvalidLocationError(
                INVALID_COUNTRY_MESSAGE.format(location=location)
            )
        return country

    def list_locations(self, metric: str | None = None) -> list[LocationGroup]:
        if metric is not None:
            metric = resolve_metric(metric, self.SUPPORTED_METRICS, self.DEFAULT_METRIC)
        groups: list[LocationGroup] = []
        if metric in (None, "price"):
            groups.append(
                LocationGroup(
                    "Bidding zones (metric: price)",
                    dict.fromkeys(sorted(ENERGYCHARTS_ZONES.values()), ""),
                    "Case-insensitive, e.g. 'DE-LU', 'IT-North'.",
                )
            )
        if metric in (None, "renewables"):
            groups.append(
                LocationGroup(
                    "Country codes (metric: renewables)",
                    dict.fromkeys(sorted(EU_RENEWABLES_COUNTRIES), ""),
                    "Lowercase two-letter codes, e.g. 'de', 'fr'.",
                )
            )
        return groups

    def get_max_duration_minutes(self, metric: str | None = None) -> int:
        metric = resolve_metric(metric, self.SUPPORTED_METRICS, self.DEFAULT_METRIC)
        if metric == "price":
            # Nominal "today + tomorrow" day-ahead window, lop off one 15
            # min step from the end. Actual data availability can be less
            # than this near local noon CET, before the next day's auction
            # results are published.
            return 2865
        # renewables: this endpoint only appears to return "today"
        # regardless of the requested range, so declare a modest
        # single-day nominal maximum instead.
        return 1425  # nominal "rest of today", lop off one 15 min step

    def get_temporal_resolution_minutes(self, metric: str | None = None) -> int:
        resolve_metric(metric, self.SUPPORTED_METRICS, self.DEFAULT_METRIC)
        return 15

    def get_data(
        self,
        timestamp: datetime,
        location: str | None = None,
        metric: str | None = None,
        headers: dict[str, str] | None = None,
    ) -> Timeseries:
        """
        Get data from the Energy-Charts API

        This method creates a URL for the request in a format that supports
        caching, gets the data, and converts it into CATS internal data format.

        :param timestamp: Timestamp from which to start forecast data retrieval
        :param location: Bidding zone ('price') or country code ('renewables')
        :param metric: One of "price" (default) or "renewables"
        :param headers: Optional, not used by this provider
        :return: Timeseries as a list of PointEstimate classes
        """
        metric = resolve_metric(metric, self.SUPPORTED_METRICS, self.DEFAULT_METRIC)

        start_time = align_to_resolution(
            timestamp, self.get_temporal_resolution_minutes(metric)
        )
        end_time = start_time + timedelta(minutes=self.get_max_duration_minutes(metric))

        if metric == "price":
            location = self._validate_price_location(location)
            # Some zone codes contain characters that are unsafe unescaped in
            # a URL query string (e.g. "IE(SEM)"), so quote it.
            url = (
                f"{self.base_url}/v2/price?"
                f"bzn={quote(location, safe='')}&"
                f"start={start_time.strftime('%Y-%m-%dT%H:%M:%SZ')}&"
                f"end={end_time.strftime('%Y-%m-%dT%H:%M:%SZ')}"
            )
            response: dict[str, Any] | None = fetch_url(url)
            # location has already been validated against the static zone
            # list above, so a missing/empty "data" field indicates a
            # genuine upstream/availability problem rather than a bad location.
            assert response is not None, "No response from Energy-Charts price request"
            assert response.get(
                "data"
            ), "Empty response from Energy-Charts price request"
            values = [
                PointEstimate(
                    datetime=datetime.fromisoformat(d["timestamp"]),
                    value=d["values"]["day_ahead_price"],
                )
                for d in response["data"]
            ]
            return Timeseries(
                "Day-ahead electricity price", values=values, unit="EUR/MWh"
            )

        # metric == "renewables"
        location = self._validate_renewables_location(location)
        url = (
            f"{self.base_url}/v2/signal?"
            f"country={location}&"
            f"start={start_time.strftime('%Y-%m-%dT%H:%M:%SZ')}&"
            f"end={end_time.strftime('%Y-%m-%dT%H:%M:%SZ')}"
        )
        response = fetch_url(url)
        assert response is not None, "No response from Energy-Charts signal request"
        assert response.get("data"), "Empty response from Energy-Charts signal request"
        values = [
            PointEstimate(
                datetime=datetime.fromisoformat(d["timestamp"]),
                value=100 - d["values"]["share"],
            )
            for d in response["data"]
        ]
        return Timeseries("Non-renewable share", values=values, unit="%")
